# Generated by Django 3.2.4 on 2021-06-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.CharField(max_length=64)),
                ('num2', models.CharField(max_length=64)),
                ('oper', models.CharField(max_length=64)),
                ('result', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.CharField(max_length=256)),
                ('correct', models.CharField(max_length=64)),
                ('wrong1', models.CharField(max_length=64)),
                ('wrong2', models.CharField(max_length=64)),
                ('wrong3', models.CharField(max_length=64)),
            ],
        ),
    ]
